### ISSUE TITLE
Safehouse Raid wave counter broken for clients

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#105]
As of today's patch (3.11.2016), the wave counter in the Safehouse Raid heist doesn't seem to work for clients. The host sees waves counter properly, but clients only see Wave 0/3 the whole time. We tested this pretty thoroughly, trading host duties around and it stayed consistent. All players involved in the testing (those I could ask directly) were also running WolfHUD.

**Comment by Tatsugi** [comment]
Change a number of month, 10 -> 11.

**Comment by Kamikaze94** [comment]
Added a new function that updates the wave text. (Because Overkill did so for their label...)
Still only showing wave 0, not working properly. On a sidenote, got it to display wave 3/3 after reconnecting (because it crashed).
Looks like the assault wave gets synced on start, but doesn't get updated on assault end/start for clients....
Not sure if this issue is WolfHUD specific or in the base game though...
