### ISSUE TITLE
settings not been remembered in the beta version

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#11]
They're remembered, but reset when you restart or exit heists

**Comment by Kamikaze94** [comment]
Which settings don't get saved? All of them?
 Also, some options you see in the menu of the beat version are currently not implemented anymore, due to changes in CustomHUD and needed changes in scripts that work with default or customhud.
Nope, Inventory Pages file gets moved to your save folder. Basically did this, because it felt like it belonged there more, than directly in the mods folder.

**Comment by Hulkfog** [comment]
I only noticed interaction and weapon lasers options
The inventory pages forgot to check the code,
Makes mores sense in the saves folder and now displays

**Comment by Kamikaze94** [comment]
Hmm, tested out a little, but it doesn't seem that I can get it to not save my setting...
Granted my version over here is a little ahead, but I only changed settings to CustomHUD applying instant and updating HUDList. 
I havn't pushed it, cause HUDList seems to have some problems at the moment, crashing my game, ^^
But back to your problem, does BLT write any error to your log? And does your mods/saves/WolfHUD.txt look "normal"? I can only think of it having problems to write to the file. 
Btw, it only saves your settings once, you leave the main WolfHUD settings menu, not if you crash or alt-F4 out of the game, (I don't think you are, just for completeness, :P).

**Comment by Hulkfog** [comment]
No problems saving to the file
Show melee timer doesn't seem to save
Enable HudList doesn't always apply
The interaction and weapons laser option seem ok now after deleting the save file

**Comment by Kamikaze94** [comment]
Just checked the Melee timer options, and still wondering, what happens there....
As long as I go back to Mod Options, it all saves fine for me. I can even kill the game via taskmanager at that point, and the settings are saved, ^^
So, I cannot really do much, as long as I cannot reproduce the problem you have, but I can give you two options on how to (hopefully) narrow the problem down.

**A)**
Please open _'mods/saves/WolfHUD.txt'_ and confirm, it has stored your settings.
Then change the setting, go back to mod option menu, open the file again and confirm, the setting has been changed. Then restart the game, open the file again, and check, that it doesn't changed.
If it doesn't change in second open, it doesn't write properly, otherwise it doesn't read properly.  
  
**B)**
Just updated the beta branch with somne more debug lines. 
You should also consider, going to __Core.lua__ and setting *DEBUG_MODE* to _true_. 
Change around with the settings and look into your log for errors afterwards. 
Oh, and turn _DEBUG_MODE_ off before actively playing, you'll get frame freezes like hell...

Hope this helps!

**Comment by Hulkfog** [comment]
Thanks managed to fix it
