### ISSUE TITLE
Suggestion: Menu Option For Speed of Auto Pickup

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#111]
Could a option to change the speed of auto pickup be added to the options menu? I find it's sometimes faster to mash interact than hold it to pickup loose loot.

**Comment by Kamikaze94** [comment]
Don't think an ingame option would be useful here.
The old value (I think it was 0.3 secs timeout) was just some general value I assumed a long time ago, in order to prevent glitches, or stuff accidentally not counting or anything that might happen, if you instant absorb everything in range. (And that would be a little too easy, I guess...)

I lowered the value to 0.2 secs timeout now, and moved it to the WolfHUDs tweak file.
Feel free to play around with that value, and maybe suggest a better one in the future :)

**Comment by NerdVenom** [comment]
Alright, thanks. I'll try it out and see if it needs tweaking.
