### ISSUE TITLE
WolfHud resets its settings whenever I join a heist

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#112]
Kind of an annoying issue with the latest dev build. I get it all set up how I want, join a game, and see everything is back to the default settings, CustomHud and all. The json file with all my settings is still there in the saves folder, so maybe it's not reading it properly or something.

Also, I got a crash shortly after starting a Biker heist.
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/597491/crash.txt)

Update: I checked the BLT logs and found this, not sure if it's related to the settings issue:

05:30:06 AM Lua: [Mods] Loading mod: WolfHUD...
05:30:06 AM FATAL ERROR: mods/WolfHUD/Core.lua
05:30:06 AM FATAL ERROR: mods/base/req/json.lua:366: Unexpected character at Line 1 character 4419: ] (93) when reading array ({ or [ or ' or " or number or boolean or null expected)
Context: 
false,"custom_inv_tab_names":[],"show_angeled_sight":false,"d
                              ^

**Comment by Kamikaze94** [comment]
Alright, thanks for the report.
Forgot a simple check on the killer. Add that now.

For the other one, thanks as well :)
Since you can change Inventory names ingame now, I added a table to the settings which stores your customized names. Totally forgot, that BLTs json class doesn't handle empty tables well.
For now, I just added a dummy entry to it, to solve this bug.

I think these json issues a re already resolved in BLTs GitHUB repo, but aren't published since quite a while for whatever reason.

**Comment by killrhythm09** [comment]
Thanks, updating now.

Also, this is a really minor nitpick, but the correct spelling for the "fixxed" label would be "fixed."

**Comment by Kamikaze94** [comment]
Happy now? ^^
Liked the old spelling more :P
