### ISSUE TITLE
Strange bug with interactions

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#114]
I didn't really know how to explain this one, so I recorded myself playing (and eventually getting killed) on Biker D1:

https://youtu.be/JGtZdn37gm0

Notice how various interactions (picking things up, reviving people, repairing drills, etc.) are all "shorter" than they should be? It's like it's skipping part of the timer for some reason. It's a little game-breaking because it lets me do a lot of things faster than I should be able to.

I'm pretty confident this is related to WolfHud because I never experienced it before I started using this mod, but just in case, here is a list of other mods I'm using. 

02:00:54 AM Lua: [Mods] Loading mod: base...
02:00:54 AM Lua: [Mods] Loading mod: Enhanced Hitmarkers...
02:00:54 AM Lua: [Mods] Loading mod: Enhanced-Fast.Net...
02:00:54 AM Lua: [Mods] Loading mod: Lobby Inspect...
02:00:54 AM Lua: [Mods] Loading mod: Lobby Player Info...
02:00:54 AM Lua: [Mods] Loading mod: Newbies go back to overkill...
02:00:54 AM Lua: [Mods] Loading mod: PocoHud3...
02:00:54 AM Lua: [Mods] Loading mod: WolfHUD...

I can also try disabling all of them and seeing if I can recreate the problem if it will help.

Important note: for some reason, I've only experienced this on Biker D1. Maybe it's possible elsewhere, but I don't recall seeing it. Let me know if you need any other info.

Oh, and this is on the latest dev build, as always.

**Comment by Kamikaze94** [comment]
Hmm, that really looks strange...
Never experienced that, nor did a mate I asked if he had this happen...
From the appearance of it, I'd say, its getting the total interaction time correctly, but calculating the progress wrong.

Only other mod you use, that changes around with interactions is PocoHud. Maybe its a conflict some where there?
Also does it happen that regulary? As in the video, it happened quite a lot.

Really not sure, whats going on there. I doubt its happening only on Biker heist then, would make it even more strange...

**Comment by TheRealElysium** [comment]
I can confirm this, and I am not using mods that change interactions. No PocoHud.  Glitch happens 100% of the time on day 1 biker heist and sometimes on other maps but I don't have specifics right now.  It has also happened in the middle of a game before where it was previously working okay.  Once the glitch happens, the effect is persistent until a load. I'll pay more attention to where and when it happens and report back.

**Comment by TheRealElysium** [comment]
I found the source of the issue, it is being caused by slow motion.  The amount of time you are in slow motion is being added to all future interaction progress in the current mission.  Also, your slow motion boolean does not seem to work properly.

**Comment by killrhythm09** [comment]
Oh wow. Suddenly it all makes sense. Thanks for looking into it, Elysium.

**Comment by Kamikaze94** [comment]
@TheRealElysium 
Are we talking about the amsk up slow motion here? Or the getting downed slow motion?
Do you have the option to disable the slow motion effects on or off?

The option prevents slow motion effects that get triggered by your local game. Since Hotline Miami Heist, slow motion can also be synced (even as non-host, see StopTheCheater... OVK, wtf are you doing), so thats why those slowmo effects are still beeing executed. 

Btw, still not sure how this time ends up on interaction progress, but guess I'll have to find out... ^^

**Comment by TheRealElysium** [comment]
I can't say for sure if the downed slow motion is causing it but I know the mask is for sure.  I don't see why they would be handled any different however since the code executing it is basically doing the same thing.

Upon further inspection it would appear that the slow motion option only works as a host which is not ideal and could cause desync issues but that is payday for you.

Slow motion messing with the interaction progress really didn't make much sense to me either since I've previously been using all of Seven's mods as stand alone up until a couple weeks ago and I have never experienced anything like this.  I can't explain it, but I am 100% positive that slow motion is tied to this issue in some way or another.

**Comment by killrhythm09** [comment]
Just stopping by to say I tried this with the latest development build of WolfHUD and it still happens.

**Comment by Malidictus** [comment]
I have the latest Dev Build of WolfHUD from 14 hours ago. This bug is still in it.

**Comment by NerdVenom** [comment]
The "No Slow Mo" option appears to have no effect at all either.

**Comment by Malidictus** [comment]
That too - the option to disable slow motion doesn't seem to work currently.

**Comment by killrhythm09** [comment]
Honestly I never saw the appeal of that feature. Would it be easier to just remove it entirely? It seems like it causes more problems than it's worth.

**Comment by Malidictus** [comment]
Slow motion tends to induce desync more often than not, plus it's generally annoying. I'm honestly fine either way since it's Kamikaze's mod, but I'd personally prefer a fix over an outright removal.

**Comment by SomePlayer** [comment]
Also happens often if not every time on Panic Room

**Comment by dribbleondo** [comment]
The Interaction bug has returned -_-
https://clips.twitch.tv/PlayfulBoldMeatloafCharlietheUnicorn

Captured on Stream, but is known to affect Panic Room and First World Bank too.

**Comment by Malidictus** [comment]
Yeah, it was gone for a while but it's back now. I wonder what happened.
