### ISSUE TITLE
Bug: WolfHUD Broken as of latest commit

### ISSUE THREAD

**Issue by dribbleondo** [Kamikaze94/WolfHUD#117]
I get these two lines **[printed in the Linux Terminal](http://imgur.com/a/N3KUU)** endlessly after the latest update to the github version of WolfHUD.

> 10:40:29 AM Lua: [WolfHUD] ERROR: Requested setting doesn't exists!  (id='use_wolfhud_textures', type='boolean') 
10:40:29 AM Error: lua_call: error in lua_pcall: mods/WolfHUD/Core.lua:546: attempt to index global 'SystemFS' (a nil value)

Using BLT4Linux instead of the Regular BLT, but this shouldn't matter too much.

**Comment by Kamikaze94** [comment]
Hmm, the code this is originating from shouldn't even be executed on linux....
It's all for those mod_overrides.

The first one is because wolfhud_textures is the mandatory mod_override, that has no setting, probably happens on Windows as well (once), unless it creates the folder.

Second one is the class that can create folders (without os.execute stuff, means it doesn't use cmd.exe in the background and therefore minimizes the game...). That class, probably implemented in the C++ part of the game was introduced with the Workshop support for the game. Not sure why it doesn't exist for you. Is the linux build lacking workshop support?

All of the code is basically useless for linux users, because there is no support for mod_override format, therefore it should quit in Core.lua, line 530: 
`if SystemInfo:platform() ~= Idstring("WIN32") then return end`
Never thought the game returns linux as "WIN32" platform.....

**Comment by dribbleondo** [comment]
> Is the linux build lacking workshop support?

Yes. The devs actually gave a somewhat reasonable excuse of "focusing resources elsewhere".

I've no Idea why the Linux port is being identified as "WIN32", rather than it's own ID string. This is very odd behaviour! =)

**Comment by Kamikaze94** [comment]
> I've no Idea why the Linux port is being identified as "WIN32", rather than it's own ID string. This is very odd behaviour! =)

Hmm, this actually makes kind of sense, since the consoles and PC version seem to be build onto the same lua base. The code quite often checks for the platform when it comes to unique parameters for PS4/XBone, etc.
Maybe this was done in order to not have to change all checks inthe code for Win or Linux.

The lacking SystemFS class is sad though, so I cannot use this to create the necessary folders....  :(
Anyways, it logs missing folders, so it shouldn't be too bad. Plus its only needed for the preplanning manager atm. (Will probably still notify you for missing folders for WolfHUD_Textures, until I find a way of detecting the OS with lua, in a hopefully not too hacky workaround, :| )

**Comment by Kamikaze94** [comment]
Closing, as you said its fixed in the comments to commit 92d11c2d5c599be426b0cbc205faf8b47f4e3ff2.
