### ISSUE TITLE
VoiceNote Crash

### ISSUE THREAD

**Issue by Shad0wlife** [Kamikaze94/WolfHUD#120]
I have an issue with Seven's VoiceNote script which seems to crash when being activated. Since it adds a Hud element I guessed WolfHud might be the issue, and if it isn't, I'd like to ask if you could implement the feature. 
VoiceNote is a mod which displays a little speaker symbol next to a player's name if he's using the voice chat.

The crashlog:

```
Application has crashed: C++ exception
mods/VoiceNote/voice.lua:15: attempt to call method 'set_voice_com' (a nil value)

SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
-------------------------------
Current thread: Main
-------------------------------
```

I'm on game version 1.57.96 and WolfHud v2.40.

**Comment by Kamikaze94** [comment]
Alright, your problem is probably appearing since VoiceNote tries to call the method "set_voice_com" of the Teammate Panel. CustomHUD Overwrites the Teammate panels with a custom class, that doesn't have these function. Thats what is crashing it.

CustomHUD comes with a little speaker icon, if a player is using voice chat, so its already implemented.
If using CustomHUD, you don't need the VoiceNote mod, otherwise VoiceNote should work without problems :)

**Comment by Tatsugi** [comment]
Offtop: Am I blind or why I can't find VoiceNote mod? Tried to search in different ways.

**Comment by Shad0wlife** [comment]
I guess it was removed with all ot the other single scripts by Seven (like when HudList disappeared for a while). Got it off the Steam community quite a while ago...
