### ISSUE TITLE
Crash when putting body into bodybag

### ISSUE THREAD

**Issue by TheButtSmuggler** [Kamikaze94/WolfHUD#13]
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/279449/crashlog.txt)

Using the skill overhaul beta, crashes when bagging stuff.

**Comment by Kamikaze94** [comment]
Hmm, Detailed Carry Info is crashing your game.
The old version of CustomHUD overwrites hudtemp, for its own bag panel. That's why you are crashing.
The new version (found here at beta branch) just hides the default panel. That version doesn't crash, but hiding the panel means Detailed Carry Info has no use here.

You can see the bag value, for all loot in the pickup text, when looking at it. 
The carried loot type gets displayed too.
If you want to see directly how heavy a specific item is, I can recommend 'Bag Countours'. It can be found at 'paydaymods.com/mods' and is a really handy mod, so you can see how heavy a bag is, before even picking it up.
The other solution would be to disable CustomHUD in the WolfHUD settings. This way you can still use Detailed Carry Info, but loose the awesome hud layout. 

The choice is yours, ;)

PS: If you really want both, you can try using the beta version, opening WolfHUD/lua/CustomHUD.lua, scroll to the end and remove the line: "self._temp_panel:set_alpha(0)".
It will look out of place and kinda ugly, but the only way to see the detailed infos of that mod.
