### ISSUE TITLE
Crash When Assault Starts

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#139]
Game crashes when the assault starts. 

Crashlog

`Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:146: attempt to index field '_wave_text' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------`

**Comment by dribbleondo** [comment]
As a follow up to this, Muting Contractors voices leads to the same error as above, and Assaults do not end (or spawn any cops bar snipers). You can't finish the heist either.

I recorded the behaviour [here](https://www.twitch.tv/videos/118751525)

**Comment by Nemesis1021** [comment]
Same thing happened to me .. Do you know any to fix this before the mod gets updated?

**Comment by NerdVenom** [comment]
Only way to temporarily fix it, is to add the line "if true then return end" to the top of "AdvAssault.lua". This makes the game playable again, but now the Assault ticker is shoved into the right corner and HudList overlaps with it. This also disables any WolfHUD features for the Assault Banner.

**Comment by Nemesis1021** [comment]
Alright , thank you!

**Comment by Malidictus** [comment]
I just had the same crash, as well. It doesn't seem to matter if I have Advanced Assault enabled or disabled. Seems like the assault banner isn't able to read the info it needs to display for some reason.

**Comment by NerdVenom** [comment]
I believe this is because of the change to the New Safe House Raid wave counter. They patched it in U130 so that it correctly updates for clients. In doing so, they must have changed something that WolfHUD relied on.

**Comment by king121t** [comment]
I had the same problem. Thanks for the temporary solution. Please inform me what the problem is solved. Thank you

**Comment by Malidictus** [comment]
Plot twist! The crash is in the Dev Version only. The Live version doesn't have it. As a stopgap solution, I would suggest downloading the Live version of the mod and using its AdvAssault.lua instead. You don't need the entire Live mod, just grab that file and over-write the Dev Build version of it in your Mods/WolfHUD/Lua folder. I don't know exactly what the issue is.

From a quick Text Diff comparison, it seems like the Dev version has special code to handle Point of No Return timers (not relevant to the crash) and new code to handle wave numbers - lines 145 to 150. The crash occurs on line 146. This leads me to believe that this is indeed an issue with WolfHUD trying to fix Overkill's bug in syncing wave numbers having now been rendered broken by changes Overkill have made.

It might be entirely possible to retain the Dev Build AdvAssault.lua and just get rid of the override for HUDAssaultCorner:set_assault_wave_number(...). My impression is this function either no longer exists in the base game or else isn't being given the values that WolfHUD expects. Since I don't know the internal structure of WolfHUD, though, I'm going to keep the Live AdvAssault.lua because that seemed to work before the fixes.

**Comment by NerdVenom** [comment]
Gonna repost this here for anyone that needs it. 

User test1 from Steam Forums:
Try the following it restores the wave counter and should fix the crashing
http://pastebin.com/PkDUQUZd

**Comment by TheRealElysium** [comment]
This happens because set_assault_wave_number is now being called in sync_start_assault.  WolfHUD has modified set_assault_wave_number to set the assault_panel to change based on the assault wave, but this data is only defined during a safehouse raid. set_assault_wave_number calls this data but it has not been set, so the game crashes.  While I'm sure the above fix prevents a crash, it isn't really a solution to the problem.  I've wrapped calls to _wave_text in a check for the safehouse raid, which should retain the intended functionality and prevent crashes.  This may not be the cleanest solution but it is what I've come up with.

`	function HUDAssaultCorner:_animate_wave_started(...)
		if self:is_safehouse_raid() then
			self._wave_text:set_text(self:get_completed_waves_string())
		end
		
		return _animate_wave_started_original(self, ...)
	end
	function HUDAssaultCorner:_animate_wave_completed(...)
		if self:is_safehouse_raid() then
			self._wave_text:set_text(self:get_completed_waves_string())
		end
		
		return _animate_wave_completed_original(self, ...)
	end
	
	function HUDAssaultCorner:set_assault_wave_number(...)
		if self:is_safehouse_raid() then
			self._wave_text:set_text(self:get_completed_waves_string())
			self._wave_text:animate(callback(self, self, "_animate_wave_text"))
		end
			
		return set_assault_wave_number_original(self, ...)
	end`

**Comment by NerdVenom** [comment]
Latest commit by Kamikaze has fixed this issue.
