### ISSUE TITLE
[Beta] Crash when looking at turret

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#15]
So when I look at the Swat Turret, my game freezes then crashes. Even just trying to drive into one on Meltdown crashed my game. Doesn't matter if I have the Healthbars enabled or not.

Got this in the crashlog:

---------------------------------------------------------------------------------------------------------------------

Application has crashed: C++ exception
mods/WolfHUD (Beta)/lua/EnemyHealthbar.lua:272: attempt to index a nil value

---------------------------------------------------------------------------------------------------------------------

I'm also using PocoHUD and Goonmod if that helps.

**Comment by Kamikaze94** [comment]
Yeah, seems, like the turret van is in the slot_mask slot of vehicles, not turrets/sentries.
Only tested with ceiling turrets, wich worked fine...^^
Just tested the fix on Meltdown Overkill and it seems to work.
Thanks for reporting.

**Comment by Kamikaze94** [comment]
Edit: Btw, was the turret active or inactive when that happened?

**Comment by NerdVenom** [comment]
Turret was inactive. Must have crashed right when it was gonna popup and shoot?

**Comment by Kamikaze94** [comment]
Okay, so the turret van is in _divable_ vehicle slot, and in the sentry slot, if the turret is active.
The ceiling turrets are always active, or dead, therefore I didn't experience the crash when testing.

You crashed, because the turret van is missing the class, that actially handles the that the vehicle is _drivable_ (and contains the vehicle name). 
The script tried to access that class, but the swat van don't have it, cause they aren't divable, which caused the crash.

**Comment by NerdVenom** [comment]
Ah ok, cool. Well I just played Meltdown on OVK and it seems fine now. Thanks for the fix.
