### ISSUE TITLE
Crash when i die

### ISSUE THREAD

**Issue by zeviil** [Kamikaze94/WolfHUD#163]
Hi, i have this pb from only 2day ago. I havent modify anything 

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

payday2_win32_release (???) ??? 
payday2_win32_release (???) ??? 
payday2_win32_release (???) ??? 
payday2_win32_release (???) zip_get_name 
ntdll (???) RtlReAllocateHeap 
ntdll (???) ZwQueryVirtualMemory 
KERNELBASE (???) VirtualQueryEx 
KERNELBASE (???) SetUnhandledExceptionFilter 
KERNELBASE (???) SetUnhandledExceptionFilter 
payday2_win32_release (???) ??? 
payday2_win32_release (???) zip_get_name 

-------------------------------

Current thread: Main

-------------------------------

System information:
Application version : 1.64.0
CPU : Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
DirectX : 12.0 
GPU : NVIDIA GeForce GTX 960 / nvd3dum.dll[21.21.13.7849]
Language : @IDaadeda58d8e5a71d@
Memory : 8123MB 108KB
OS : 6.2.9200 () 0x300-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Microsoft (Haut-parleurs (2- USB Audio Device))

**Comment by msgtmartin** [comment]
if this is the same as what i have found it is a direct result that has something to do with the perk swan song. 

the way  i have narrowed this down is removing all mods and mods 1 by 1 and also fresh install of blt and wolfhud and testing different loadouts (none had swan song) and then on the original loudout i had the problem with i removed swan song because the problem would not occur during a down but at the very end of swan songs duration when i would be in the downed state that someone could revive me and that is the best way i could narrow it down

log files are attached
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/782007/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/782009/crashlog.txt)

**Comment by mmaffa** [comment]
I also had the crash occur when I was downed, and I also had Swan Song active. On my other build (without swan song), I was able to die without crashing.

[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/782040/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/782041/crashlog.txt)

**Comment by Malidictus** [comment]
They did a fix for the Swan Song effect lingering after the player had been revived, so that could have thrown a monkey wrench into the works with WolfHUD.

**Comment by katabamia** [comment]
hey @Kamikaze94 ,
[`lua/GameInfoManager.lua L2-L12`](https://github.com/Kamikaze94/WolfHUD/blob/master/lua/GameInfoManager.lua#L2-L12) and some files using `string.format()` to print log, but the argument thrown without `tostring()`
You must convert args to string before throw to them.

**Comment by syndencity** [comment]
same issue - probably because of the update because it happened only today, and i use swan song in every build

**Comment by syndencity** [comment]
hopefully a fix for this will come out soon

**Comment by FlamingFox911** [comment]
There has been a temporary butchering fix on Reddit here: https://www.reddit.com/r/paydaytheheist/comments/5ui53q/u132_wolfhud_swan_song_crash_temporary_fix/ I hope this helps.

**Comment by syndencity** [comment]
it worked, thanks
