### ISSUE TITLE
Проблемы

### ISSUE THREAD

**Issue by pipoch** [Kamikaze94/WolfHUD#193]
Запускаю PayDay2 с модом WolfHUD и он вылетает сразу после запуска, что делать?

**Comment by FlamingFox911** [comment]
Я рекомендую удалить папку WolfHud и ее сохранение из каталога Payday. Затем загрузите последнюю версию WolfHud (НЕ выпуск, получите главный каталог [здесь](https://github.com/Kamikaze94/WolfHUD/archive/master.zip)). Попробуй.

**Comment by pipoch** [comment]
Не работает всё также

**Comment by FlamingFox911** [comment]
Можете ли вы опубликовать последний журнал аварии? Вы можете найти его на:
`%LOCALAPPDATA%\Payday 2\crash.txt`

**Comment by pipoch** [comment]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/849963/crash.txt)

**Comment by pipoch** [comment]
В чём была проблема я не понял, я просто удалил БЛТ и все моды и заново установил по другой методике и всё заработало

**Comment by FlamingFox911** [comment]
Возможно, это поврежденный файл. Я никогда не видел такую же ошибку. Но, я рад, что все работает снова. Если мне пришлось угадать проблему, из журнала сбоев произошла ошибка в инкапсуляции кода, которая привела к ее сбою.

To anyone understanding English: The issue seems to have resolved by removing all mods and the BLT, then reinstalling it. I assume it might have been a corrupted file.

**Comment by Kamikaze94** [comment]
The issue was BLT's json class had problems decoding a json formatted file, it seems.
some file that also contains "sa_pagers_4" might have been malformatted.

Anyways, closing since it seems to be unrelated to WolfHUD and fixed :)
