### ISSUE TITLE
Crash upon finishing Conversion of enemy. (100.2)

### ISSUE THREAD

**Issue by Alchanii** [Kamikaze94/WolfHUD#20]
Was kind of surprised! Usually I can riddle these crashes out and fix them myself, but, this one eludes me.

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:1289: attempt to perform arithmetic on field '?' (a nil value)

**Comment by Kamikaze94** [comment]
You are on the version from paydaymods/lastbullet, not the dev version, right?
Looks like it has something to do with the "Partner in Crime" skill.
Do you have that skill (basic/aced)?

EDIT: 
Okay, tried all the combinations of minion buffing skills, cannot seem to find any, that would crash me (tested on dev version, but the same line your crashlog mentions is in there too...)
Not quite sure, why you are crashing. Do you run any gameplay changing mods, that modify the upgrade values?
Maybe try the dev version (was about to push it anyways, so... :), and check if that problem persists?

**Comment by Alchanii** [comment]
Correct on the lastbullet part, maybe that is my first mistake.
Yes to Partner in Crime. Aced. I main Mastermind, even if this detail is kind of irrelevant.
The only things I have that modify perks in any single way -- and they're disabled/out of the mod folder -- is stuff that makes Inspire take priority over everything else. So, no, (un?)fortunately.

I'll gladly try the dev version and see if it continues. If it does, I'll continue my own efforts to figure out what's (potentially) conflicting. Been in this situation so many times, I'm aware of the scenarios where Mod A does not interact with Mob B/C/etc at all, can make either party not play nicely together.

**Comment by Kamikaze94** [comment]
Hmm, the crash is occuring, because this: "tweak_data.upgrades.values.player.passive_convert_enemies_health_multiplier[partner_in_crime_level]" returns a nil value.
Meaning, your passive convert table is smaller than it should be, or the partner in crime level gets higher than it should.
The fastest part would be to add
"(tweak_data.upgrades.values.player.passive_convert_enemies_health_multiplier[partner_in_crime_level] or 1)", but that would probably make the minion healthbar inaccurate.

Can you add above those line it crashes:
log(tostring(partner_in_crime_level))			log(json.encode(tweak_data.upgrades.values.player.passive_convert_enemies_health_multiplier))
and look up the values, it logged to your BLT log?
Obviously, the first should be 1 or 2 (0 if you don't have partner_in_crime), the second giving you a table with two values.

Then, we are one step closer, to why that error happens, :)

**Comment by Alchanii** [comment]
Yeah, sure!

Did that, and I'll admit I've not had to do this before, however, I assume that the data I needed went to the 2016_06_09 log, and not anywhere else? If so, upon converting an enemy and crashing, I got this: 04:29:23 PM Lua: 4
04:29:23 PM Lua: [0.55000001192093,0.10000000149012]
04:29:26 PM Log: CURL CLOSED

I'm not a modder for payday 2, I don't dig too deep into it, but... That looks wrong.

**Comment by Kamikaze94** [comment]
Oh, your partner_in_crime_level is for some reason 4, but the table for that skill is only 2 in size, because there are only max  2 levels.
Something is messing with that stuff somewhere.
Only thing I can do about it, is cap the level somewhere manually, so the crash doesn't occure, but data may become inaccurate (+ its a kinda messy solution). 
The mayor question now is, what is incrementing, or multiplying that level by 2?
My best guess would be, probably another mod, as noone reported anything in that direction, and I cannot get the bug to occure on my end.

(Very small chance, but depending on your internet connection, you might want to verify game cache, just in case...but I wouldn't count on that fixing it.)

**Comment by Alchanii** [comment]
I can only offer my deepest shrug while I do the verify. Maybe my installation got weird once the new skill trees happened. I'll continue chopping away, I suppose. Maybe use that line you mentioned earlier, even if it will make the minion health weird. See if that stops the crash from happening, 'cause, if it does, I'm totally fine with that trade-off.

It's funny that I was supposedly getting Ace Plus and Ace Plus Plus on that specific ability, according to this information. But since the effects don't exist, me somehow getting "4 out of 2" on that skill is meaningless.

**Comment by Kamikaze94** [comment]
Already made a few changes. In case you redownloaded WolfHUD from here, that may have fixed it.
Maybe resetting the skills did, and something was bugged there, we'll probably never know, : P
Anyways, nice, that its working now, and happy heisting, ^^
