### ISSUE TITLE
HOXTON: SAFEHOUSE CHOOSE CONTRACT IN CRIME.NET

### ISSUE THREAD

**Issue by chromKa** [Kamikaze94/WolfHUD#222]
![20170405173308_1](https://cloud.githubusercontent.com/assets/19959081/24716040/276fd6ae-1a36-11e7-91bf-e8bc739c7194.jpg)
I dont know why, but if you set SAFEHOUSE appear "CHOOSE CONTRACT IN CRIME.NET" After word "SAFEHOUSE"

**Comment by Kamikaze94** [comment]
Yep, had this happen once as well.
Since ome point during crime spree, some node stuff seems to be messed up. (I always see the BLTs notification box in the stage end screen while its counting EXP. Also, when opening Mutators or Safehouse GUI in lobby, you see the normal lobby header in the top left behind the current one, harder to read but still there)
Those glitches are there even without BLT and mods at all.
Not sure if that's intentional, but seems, like Overkill did some changes to node handling/switches and something got messed up...?
