### ISSUE TITLE
Game crashes upon trying to load preplanning plan.

### ISSUE THREAD

**Issue by OhhLoz** [Kamikaze94/WolfHUD#224]
Application has crashed: C++ exception
mods/WolfHUD/lua/PrePlanManager.lua:559: attempt to index field '?' (a nil value).

I dont think this occurs every time you try to load a plan, however it occurs quite frequently.

It may be noted im not on the latest dev version, I just updated so will give further information as it happens.

**Comment by SirTartcube** [comment]
Similar Issue?
Application has crashed: C++ exception
[string "lib/managers/missionassetsmanager.lua"]:388: stack overflow



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.199
	CPU : Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 4400 / igdumdim32.dll[10.18.15.4248]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     6058MB 376KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Intel(R) Corporation (LCD TV (Intel(R) Display Audio))

**Comment by Demiu** [comment]
Can confirm, the game has crashed 2 times and both were when clicking "load plan"

**Comment by OhhLoz** [comment]
It appears to only occur when trying to load plans in crime spree.

**Comment by Kamikaze94** [comment]
Are you running the lastest dev build?
Can I get an updated crashlog, since there were some updates to the PrePlanManager, and the lines given in the crashlog aren't pointing anywere anymore.
Also, just to be sure, when you clicked "load plan" or when you clicked on a plan to be loaded?
In the second case, did you have enough money/favours?

**Comment by OhhLoz** [comment]
Whilst I updated to the latest build yesterday, I have yet to test it for this issue. It occurred when pressing the "load plan" button. Not when clicking a plan to load.

**Comment by Demiu** [comment]
When clicking "Load Plan", not actualy loading one. Will later check if master shares this problem

**Comment by OhhLoz** [comment]
On a sorta off-topic note, when loading a plan on a bank heist, half the time there is no thermal drill on the map so you cant complete it.

**Comment by Demiu** [comment]
You have to explicitly choose a plan B in the planer and then save.

**Comment by Kamikaze94** [comment]
Yes, that was a bug in a previous version.
I actually messed up determining the default plan, if you didn't change it.
It saved the elment id as index. On loading the plan, it tried to vote an a non-existing plan, allowing you to vote on no plan at all.
This causes the van on bank to not spawn.

That bug is fixed, and plans are now only saved in a file per level("<level_id>.json"), so bank heist cash plans can be loaded in random, deposit, gold, etc as well (and in crime spree, without creating and saving them seperately.)
Sadly, those two bugs mean, you have to recreate your saved plans on the updated version once.
(You could migrate them by renaming the files to only the parts after the last underscore, but would still require you to manually resolve the issue with the wrong elment indexes on default plans.)
