### ISSUE TITLE
Wrong hud icon for the "Underdog" skill

### ISSUE THREAD

**Issue by HetNeSS** [Kamikaze94/WolfHUD#23]
![20160612233021_1](https://cloud.githubusercontent.com/assets/18286472/15993131/615b4f1c-30f6-11e6-86e8-c74589cffc86.jpg)
![20160612233716_1](https://cloud.githubusercontent.com/assets/18286472/15993146/baff7d18-30f6-11e6-91e9-0ce3cfba2361.jpg)

.. While no skill with that (bullets bouncing off a heister) icon is acquired

**Comment by Kamikaze94** [comment]
There is a yellow Damage Incresed, blue, damage absorbtion and purple melee damage increased icon.
Those combine all skills doing something like that into one, in order to not spam the buff list too much.
In your case, the yellow damage increased is your underdog. it says +15% under it (cause you have aced version), and the timer bar around shows you how many of your 7 seconds are left.

There are possible items for those skills seperately, but there would be soo many icons (depending on which skills you get), you waould loose track of which skill is currently active.
Thats probably why Seven used these combined Buff Items.
