### ISSUE TITLE
Latest WolfHUD issues

### ISSUE THREAD

**Issue by Jowy12** [Kamikaze94/WolfHUD#231]
1. Crews loadout doesn't show up in lobby (Normal game)
2. Ammo count works oddly, i'm using real ammo count (Doesn't work as it should be) - Fixed
3. Crews loadout in planning screen is messed up (As Client)
4. Crews loadout in Tab Stats also messed up when someone joined (As Client)
5. Bought assets keep getting announced everytime I switch profile during planning screen

**Comment by hud8614** [comment]
+ no slow motion....

**Comment by Kamikaze94** [comment]
> 1. Crews loadout doesn't show up in lobby (Normal game)

> 3. Crews loadout in planning screen is messed up (As Client)

> 4. Crews loadout in Tab Stats also messed up when someone joined (As Client)

Could reproducethose issues.
Those should be gone with the last comit.

> 2. Ammo count works oddly, i'm using real ammo count (Doesn't work as it should be) - Fixed

Looks like you found the problem with your second issue, right?

> 5. Bought assets keep getting announced everytime I switch profile during planning screen

This is part of the base game and intended (or maybe they just didn't bother with muting the reannounce).
The vanilla game locks and refunds all assets on profile switch and then rebuys them, if you still have the required skills/funds/...

Thansk for reporting :)

> no slow motion....

In case of synced mission slow-motion, like Biker day 1 and Hotline day 2, its intended.
Otherwise, it would trigger slow-motion for everybody, depending if the person masking up first has this mod active or not.

**Comment by Jowy12** [comment]
I just installed the latest WolfHUD and i got this crashlog everytime the game started

Application has crashed: C++ exception
[string "lib/units/beings/player/huskplayerinventory..."]:77: attempt to index local 'factory_weapon' (a nil value)

Also i'm testing it on Beta. Not sure if this make any different.

The loadout in lobby and planning screen is fixed.

**Comment by PasswordLost** [comment]
Whenever I start a new heist or go to the main menu, WolfHUD settings always reset themselves. Is this a mod conflict with my other mods or is this the result of a different issue? I'm using the latest non-beta version.

**Comment by Jowy12** [comment]
The issues i addressed seem to be fixed now. Thank you for the update (:
