### ISSUE TITLE
Not an issue, just asking.

### ISSUE THREAD

**Issue by Remobit** [Kamikaze94/WolfHUD#261]
I'm curious when you're planning to push a new update to the BLT servers.
It's getting a bit annoying to tell people on /r/paydaytheheistmods to download this version.

**Comment by BangL** [comment]
+1
feels like 50% of all issues on this issue tracker are just getting created because there are no blt updates.

**Comment by FlamingFox911** [comment]
The matter of the fact is that stuff on the BLT site hasn't ever been updated for a long while, including the BLT itself. I would rather stick to the GitHub versions.

**Comment by BangL** [comment]
@FlamingFox911  i think you're not getting what we mean.
you know.. the blt-servers arent just the blt website. the ingame auto-updater of our blt is getting the updates from there.
the problem is that kamikaze94 is not pushing any updates to the blt page anymore for some reason. and we are asking for the reason, since its causing alot trouble.
people are using old versions of wolfhud, because they don't download the dev version. and then they complain about bugs which are fixed already. - just because they simply dont know how to get the dev version and rely on the auto-updater. and we are getting tired of telling people how to download the dev version all the time.

**Comment by BangL** [comment]
..on the other hand it is also getting harder to take real bug reports seriously, since you never know on which version someone is.

**Comment by NerdVenom** [comment]
I agree completely with this. All I ever see on the Steam Forums under Modding is "My game is crashing" which is 90% most the time caused by an non-dev version of WolfHUD. I think all it would take, is to push the dev version to BLT with a warning that it will reset your WolfHUD options.

Slightly offtopic, but is there a way I can auto update to the latest dev version of WolfHUD?

**Comment by FlamingFox911** [comment]
Sorta. Its not really practical, but its better than nothing. Do the following:

1. Download and install the latest [GitHub Desktop](https://desktop.github.com/).
2. Go to the [WolfHUD Main Page](https://github.com/Kamikaze94/WolfHUD), click on "Clone or Download", then click "Open in Desktop".
2b. Or if you are on Windows, click [this](github-windows://openRepo/https://github.com/Kamikaze94/WolfHUD).
3. When it asks you to "Browse For Folder", navigate to your Payday2 folder and select the "mods" folder (see below).
![image](https://cloud.githubusercontent.com/assets/11638944/25878170/a9fcc02a-34f6-11e7-9f9a-c0a2027bbb52.png)
4. Hit OK. You have now created a local repository of WolfHUD directly in your Payday2 mods folder.
5. If you want to update WolfHUD to the latest, run GitHub Desktop, select the repository, then click Sync.

I hope this helps. :smile:

**Comment by NerdVenom** [comment]
Alright, thanks FlamingFox911 I'll try that out when I get the chance. 
Now let's hope Kamikaze94 sees this and gives WolfHUD stable an update.

**Comment by BangL** [comment]
#267

**Comment by BangL** [comment]
#269

**Comment by BangL** [comment]
#306
