### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by K2177** [Kamikaze94/WolfHUD#264]
I haven't updated/downloaded WolfHUD for a while, and now when I did, the info panel on the right has received some kind of outlines. How can I get rid of those outlines?

![Why](http://i.imgur.com/z12XXST.png)

**Comment by NerdVenom** [comment]
They are there because Kamikaze94 added progress bars around the HUDList items. You can notice this whenever you bag loot or a drill is going. 
Personally, I'd only like them around items that would need a bar like drills, timers or anything that takes more than 10 seconds to complete.

To remove them, I guess he'd have to add an option for it if there isn't already one.

**Comment by Kamikaze94** [comment]
Since I forgot to tag this issue in the commit, just as an update:
Added an alpha slider for progress bars for left right and buff list.
Obviously, setting the alpha to 0 will hide the bar.
Hope this answers the question :)
