### ISSUE TITLE
Failed to scan constant from string

### ISSUE THREAD

**Issue by black-silence** [Kamikaze94/WolfHUD#269]
Wolfhud writes massive logs because of unclean json, trailing commas in lists and objects.

This should be cleaned up. Example: the comma after wolfhud is invalid.
```{ "revision" : 20, "identifier" : "wolfhud", }```

**Comment by K2177** [comment]
I've recently cleaned and compacted the json myself every time I download a new version. It's a lengthy process to do again and again but I find it to be worth the effort. (Perfectionist me)

**Comment by FlamingFox911** [comment]
That has appeared in alot of the mods that are out there, mainly due to the new JSON reader that Overkill has introduced. Although the reader is better, it has issues when someone doesn't JSON correctly. Ideally, one just runs their json through this: https://jsonlint.com/ and then you are good to go.
