### ISSUE TITLE
WolfHUD's been crashing for every downed i get after swansong.

### ISSUE THREAD

**Issue by godlikesad** [Kamikaze94/WolfHUD#280]
Hey there, I'm not sure whether you've heard of this bug(though you probably do) but i tried fixing it by trying to delete the wolfHUD mod file in the payday 2 folder and it won't let me do it. Since I'm on windows 10 it says i need a administrator's approval from DESKTOP-C5DIGS4. So now i can't really play payday 2 because of the crash bug and i really need assistance for this.

**Comment by Jowy12** [comment]
Please download the Dev Version of WolfHUD. You can grab it from this site, just click Clone/Download.

**Comment by FlamingFox911** [comment]
This is a duplicate issue, and was fixed in the development version of WolfHud
https://github.com/Kamikaze94/WolfHUD/issues/234#issuecomment-294362219

Please download the latest version of WolfHud [here](https://github.com/Kamikaze94/WolfHUD/archive/master.zip).
https://github.com/Kamikaze94/WolfHUD/issues/275#issuecomment-301322959

Let us know if it works.

**Comment by ATTAFWRD** [comment]
I recommend to temporary force kill **igfxEM.exe** via Task Manager to delete **not just** WolfHUD folder **but other folders** too inside steamapps. For unknown reason (to me at least), that somehow handling almost ALL of the folders inside steamapps.

**Comment by godlikesad** [comment]
All of the folders within payday 2 too? Does uninstalling pd2 make things easier?

**Comment by ATTAFWRD** [comment]
You can always try uninstall. Trust me it will still locked. Some games even can't function properly because of this issue. Some files or/and folders will still stuck and locked by igfxEM.

**Comment by godlikesad** [comment]
Okay so just find this folder and delete the entirety of it in task manager?

**Comment by ATTAFWRD** [comment]
Yes, all you need is kill the igfxEM from task manager, then you can delete what folder you want to delete inside steamapss folder, in this case it's the woflhud folder or any other folder you want. It's because igfxEM locking them for unknown reasons you can't delete it. If you restart PC igfxEM will function normally. Actually igfxEM is Intel's signature something, you can just Google it.

**Comment by ATTAFWRD** [comment]
If you just want a fresh woflhud mod, just download from clone/download, kill igfxEM, delete the woflhud folder from mods folder, woflhud save from mods/saves, and paste your new downloaded woflhud to mods.

**Comment by godlikesad** [comment]
Thank you all so much. its finally back to work now.
