### ISSUE TITLE
Compatibility Issue With Oh Sh*t! More Profiles Mod

### ISSUE THREAD

**Issue by Sydch** [Kamikaze94/WolfHUD#283]
It seems like new feature has issues with it. I hope you can make it compatible with it someday^^

**Comment by NerdVenom** [comment]
"Oh Shit! More Profiles" mod is very outdated from what I understand, you should be using "Custom Profile Set" : https://modworkshop.net/mydownloads.php?action=view_down&did=18071
"Custom Profile Set" seems to work fine, other than having some profile names overlap with skillset names because of length.

**Comment by Sydch** [comment]
Thanks NerdVenom, i haven't saw that mod before. No more compatibility issue!

**Comment by NerdVenom** [comment]
No problem.
