### ISSUE TITLE
RE: Buy All Assets

### ISSUE THREAD

**Issue by Ongjming** [Kamikaze94/WolfHUD#290]
I remember there was this mod incorporated into wolfhud some patches back. Now I seemingly can't find this in the mod options anywhere after recent mod patches (possibly after the whitespaces removal update).
Noticed about this problem after another friend of mine pointed this out trying to disable the auto buy all assets setting (personally I disabled the auto buy all option and never looked back).

Thanks.

**Comment by Kamikaze94** [comment]
The "Buy All Assets" script never had an option, so you cannot disable it.
I rewrote the script not too long ago, be be a seperate button on the assets tab, as the previous implementation seemed to get synced to clients at times and potetially crash them.

Btw, there is no AutoBuy feature included in WolfHUD. The metioned script only does something if you click on its button. Due to its asset-bature, the previous script dispalyed beeing bought, when all assets where not available to the player, but it didn't unlock nor costed anything.

Hope this helps clearing things up, :)

**Comment by Ongjming** [comment]
Ok thanks :D Yea it definitely cleared things up for me, I am sorry for taking your time but I am a bit blur at times.
I am glad that Wolfhud doesn't have the auto buy thing. 👍
