### ISSUE TITLE
No longer showing bag values

### ISSUE THREAD

**Issue by SC2Mitch** [Kamikaze94/WolfHUD#345]
Prior to update 150 the hud was showing bag values, Like a bag of coke was worth said amount but it's no longer showing this no matter how much I tinker with the options.

**Comment by Kamikaze94** [comment]
If you are playing CrimeSpree, that's an intended change.
I added that in an earlier commit, but made a small mistake so it didn't take effect.
Fixed it in the latest commit now...

The reason is kinda simple. 
You don't get additional money for bags in a CrimeSpree, so displaying a value for them is kinda misleading.

**Comment by SC2Mitch** [comment]
Thanks!
