### ISSUE TITLE
Pre planning manager controller crash

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#369]
Clicking on load or delete plan when none exists causes the following crash
Application has crashed: C++ exception
[string "lib/managers/menu/preplanningmapgui.lua"]:2665: attempt to index local 'item' (a nil value)

**Comment by SC2Mitch** [comment]
Fairly sure this is a Payday 2 issue instead of a WolfHud issue since this: lib/managers/menu/preplanningmapgui.lua doesn't reference anything in the WolfHud files. I'd recommend posting it on the [PD2 steam forums](https://steamcommunity.com/app/218620/discussions/14/)

**Comment by Kamikaze94** [comment]
Might be a problem with WolfHUD again...
We had this problem before. Was related to the selected_item return of "MenuPrePlanningInitiator:modifiy_node_preplanning_saved_plans" function. More specifically line 141 probably.
I think I changed that to return the id of the divider instead of __nil__, because you get the selection background under the node on returning nil here.
Might have to try and change that back and live with the small glitch... :/

**Comment by Hulkfog** [comment]
In a previous commit you commented the following
Hook "PrePlanningMapGui:set_map_position_to_item", check for existence of item parameter. (causes crashes with controller, might be fixed with proper selection of selected_item now...)
Maybe that could fix the crash
