### ISSUE TITLE
Greyed Out Options

### ISSUE THREAD

**Issue by Tenkomanker** [Kamikaze94/WolfHUD#384]
Some of the options in the WolfHUD mod options menu are greyed out and unable to be changed, such as the player sentry laser color. The RGB values are greyed out and the only way to change them is by right-clicking and changing the numerical value, but this is only temporary and resets to default RGB upon game reset. Other than other numerical options like RGB colors, all greyed out options are unchangeable and clicking on them does nothing. Yes I've updated to the latest version and yes I've reinstalled WolfHUD. Is this a problem with my game or is it a problem with WolfHUD/my options for WolfHUD?

**Comment by kallak** [comment]
Can you take a screenshot of the bug?

**Comment by Tenkomanker** [comment]
@kallak so sorry a few days after this I got busy and kind of dropped Payday 2 for a few months. I have the new update of Wolfhud and the option to change the laser color for sentries among others are still greyed out. Here are some screenshots; https://steamcommunity.com/sharedfiles/filedetails/?id=1172670452
https://steamcommunity.com/sharedfiles/filedetails/?id=1172670439

Still haven't been able to figure out how to fix this and nowhere anywhere is there someone with the same problem as me so I'm thinking it's a me problem.

**Comment by Kamikaze94** [comment]
Thanks for reporting, and the screen of course :)

The first one was actually a bug, introduced in April with the addition of those options. 
Got those fixed in the last commit (1a7c5f756aafbd7a6ba721eea0394b20bd4e5fed).

Your second issue is actually intended. Since you have the rainbow mode enabled, it is supposed to disable the color selection, cause it cycles though all the colors automatically and you cannot define a custom one.
Disable that one, and the RGB silders should become changeable again.

Hoping this clears things up.  :D

**Comment by Tenkomanker** [comment]
@Kamikaze94 Thanks for the rainbow mode tip, it fixed my problem, but even after downloading the newest version the greyed out option for the timer among other things is still there. Could it be a problem on my end?
