### ISSUE TITLE
Wolfhud is gone in my game?

### ISSUE THREAD

**Issue by ALE854** [Kamikaze94/WolfHUD#445]
Haven't played Payday for a while but when I launched it yesterday I noticed that Wolfhud is gone? What happened and does anyone know a solution for restalling it again? I've got the devs version. Is the mod still updated from time to time or is it abandoned?

**Comment by ALE854** [comment]
Ok thanks. I will do that.

**Comment by ALE854** [comment]
Ok downloaded the files but what do I do with the Payday 2 BLT? Wolfhud I know to put in the mod folder.

**Comment by VolkJ-VJ** [comment]
Download  [Payday 2 BLT](http://paydaymods.com/download/) 
Installation

Hold it! Make sure you’ve installed the x86 2013 C++ Runtime before installing. If you don’t, the BLT won’t work, your game will crash, and you’ll look like an idiot when asking for help because you didn’t read the instructions.

Step 1 - Download

Download the BLT from the link above, since you’ll need that first.

Step 2 - Open your Payday 2 directory

You’ll need to open your Payday 2 directory. If you know where your SteamApps are, then go to SteamApps/common/PAYDAY 2/.
Otherwise, right-click Payday 2 in Steam and select Properties. Choose the tab Local Files and click Browse Local Files to open explorer right to it.

Step 3 - Extract

Extract the IPHLPAPI.dll and mods/ folder to your PAYDAY 2 folder from your download, and you’re done.

Step 4 - Installing Mods

BLT mods are installed by simply placing the mod folder into your mods folder.
So if you downloaded GoonMod, place the GoonMod folder into mods and you’re good to go.

**Comment by ALE854** [comment]
Do I have to install x86 2013 C++ Runtime again before I install the new version? Wolfhud worked perfectly until the latest update of Payday.

**Comment by VolkJ-VJ** [comment]
No

**Comment by ALE854** [comment]
Installed the latest BLT_release_r7_r18 and Wolfhud master but the mod doesn't show up. Don't know if I used the correct ones?

**Comment by ALE854** [comment]
Finally got it to work. Thanks for your help:)
