### ISSUE TITLE
Pistols loot called Battle Rifle according to Waypoint

### ISSUE THREAD

**Issue by BreakinBenny** [Kamikaze94/WolfHUD#458]
Self-explanatory; the pistols loot in Murky Station is considered Battle Rifles, how about that?

**Comment by MEXAHOTABOP** [comment]
probably this name from payday localization

**Comment by BreakinBenny** [comment]
So, can this somehow be dealt with? I'm certain that somewhere there is a string for the "Battle Rifle" loot. It'll be as easy as replacing the word inside it.

**Comment by Kamikaze94** [comment]
If you are taliking about the label of the closed pistol crates, thats because the interaction_id gets assigned a carry_id in GameInfoManager (lines 217 ff.). (same for all other interaction units that have no carry data assigned, e.g. you aren't picking them up by that interaction)
Since the interaction_id is the same for pistols, battle rifles and AKs, all of those get the same waypoint text assigned.
  
For the bagged pistols, it shows the correct string for me, since it is using the same localized string that gets displayed in the carry HUD.
