### ISSUE TITLE
WolfHUD mod is crashing each time i start it

### ISSUE THREAD

**Issue by Cmahen** [Kamikaze94/WolfHUD#474]
I downloaded  BLT WolfHUD  from paydaymods.com. The intro worked but once i clicked "click any button to start" the game crashed. Som1 please help!

**Comment by jtmal0723** [comment]
Unfortunately, you just stated exactly what was wrong.. The version on paydaymods.com hasn't been updated since 2016. You will need to follow the directions on the main page of this git repo in order to get the most up to date version. Be sure you completely remove the one from paydaymods first (delete that folder from the mods folder). https://github.com/Kamikaze94/WolfHUD/blob/master/README.md
