### ISSUE TITLE
WolfHUD crash with today's update

### ISSUE THREAD

**Issue by MrTactigles** [Kamikaze94/WolfHUD#49]
Thu Sep 01 11:44:28 2016

Application has crashed: C++ exception
mods/WolfHUD/lua/DamageIndicator.lua:13: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.11
	CPU : Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 680M / nvd3dum.dll[10.18.13.6881]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     412184    0MB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (Logitech G35 Gaming Headset))

**Comment by Kamikaze94** [comment]
Yep, Overkill added dynamic damage indicators as well, thats the problem here.
Just upped a quick fix, that can either enable Overkills variant or mine.
Will have to see, how well my options are integratable into Overkills version....  :)

**Comment by Malidictus** [comment]
I was just coming to report that, as well. I know the point of the dev build is to test experimental stuff, but do you think it's worth pushing a crash fix through the automatic update process? Not everyone knows to come here :)

**Comment by Kamikaze94** [comment]
I'm currently at it....
Just writing the Changelog atm.
Hope, I'm not hurrying too much and messing up BLTs update structure, :P

**Comment by hud8614** [comment]
option
mod option
wolfhud Settings
General hud panel options
DAMAGE INDICATOR ( "Dynamic Damage indicator" ON => OFF )
no Crash...
(http://www.overkillsoftware.com/games/communitysafe/)

**Comment by Malidictus** [comment]
I tried playing with the WolfHud Damage Direction Indicator turned on via the option and the game runs fine so far. No crashes of any kind and the indicator itself works as advertised. I've kept mine on just because I like the WolfHud implementation.

**Comment by Kamikaze94** [comment]
@hud8614 
Yeah, but before the update you would've crashed, no matter what you set that setting to. :)
Currently, I just updated the script to hide Overkills DamageIndicators and show mine instead, if that option is enabled. And show the Vanilla ones otherwise, as before. 
Maybe will take a look into keeping the Vanilla one and just giving options to alter the color/Circle radius/Indicator Duration.
Not sure yet, might also stay as it is...

**Comment by Malidictus** [comment]
Ideally, you'd want to retain as much of the base game's options rather than doubling them up with similar modded copies, but that depends on how much work it turns out to be. I personally prefer WolfHud's damage direction indicators since I can pick their colours, but they do occasionally show me getting shot from "behind" when I'm being shot from below at a steep angle.

Either way, the game runs without crashing now, so I'd call this at least temporarily fixed :)

**Comment by Kamikaze94** [comment]
Okay, got the damage Indicators updated/rewritten today.
Guess that eliminates the piece of purpose this issue had left... :stuck_out_tongue: 
Closed.
