### ISSUE TITLE
beta controller localization bag bug

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#5]
When using a controller it displays  $BTN_INTERACT instead of RB.to take the bag
The bag value shows correctly.

**Comment by Kamikaze94** [comment]
Okay, thanks, will need to look into this.
Just to be clear here, when you bag a pile of unbagged money, coke, etc, or when you grab already bagged loot?

**Comment by Hulkfog** [comment]
Added a screenshot
http://imgur.com/JOXqr15

**Comment by Kamikaze94** [comment]
Okay, so I guess that was not happening when you bagged for example gold or money?
Found out, the btn_macro function returns nil on controllers, instead of the default button...
Changed the interaction macros to load the default button, if btn_macro delivers nothing.
I hope that'll fix it.

PS: You can upload images here directly, afaik,  :)

**Comment by Hulkfog** [comment]
The error only occurs when you hover over a bagged bag with a controller
The fix breaks the bag value for controller and k/b and mouse.
The previous string "wolfhud_int_locked" : "PRESS [$BTN] TO INTERRUPT",works

**Comment by Kamikaze94** [comment]
Oh, yeah, somehow only commited loc changes...  :/
Added the lua ones now.
However, it seems strange, that its only occuring with loot bags, sice they both use the same localization macros....
Btw, does the button to cancel interaction, when the interaction is locked locked show up correctly?

**Comment by Hulkfog** [comment]
The bag value text displays correctly now
The macros.BTN_INTERACT fixes the bag value display in open container and bagged loot
The locked text can be fixed by restoring the function HUDInteraction:set_locked to the previous commit, but change BTN to BTN_CANCEL and it's fixes the text.
It's works with both k/b and mouse and controller with the albow change to .HUDInteraction:set_locked

**Comment by Kamikaze94** [comment]
Okay, good to hear that,  :)
Changed the locked Text macro because I thought, getting the button string by the function intended for that might be a better idea than ripping that out of the controllermanager myself.
On its basis the localization function does the same, with the difference of returning nothing when a controller is used (Why u do dis, Overkill, :/ ).
Added the default macros for those buttons there now, so I hope we can finally mark this one fixed. :D
Thanks for the help with testing and reporting, as I don't use and don't have a controller, recognized by the game.

**Comment by Hulkfog** [comment]
Thanks for fixing
It's now displays the LB, instead of left shoulder to cancel interaction.
