### ISSUE TITLE
Crash when joining to someone

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#51]
Application has crashed: C++ exception
[string "lib/units/props/drill.lua"]:907: attempt to compare nil with number

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Next is, don't know if it causing by WolfHUD, I think as modder you can tell why crashing...

Application has crashed: C++ exception
[string "core/lib/utils/corestring.lua"]:63: bad argument #1 to 'gmatch' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

**Comment by Kamikaze94** [comment]
The first one could be related to the update on determining, if you can upgrade a drill/saw or not.
Maybe a drill/saw was already placed on the heist you tried to join, and tehre were some sync problems there...  :/ 
I'll upload a version with some more checks soon.

The second one seems to be related to Overkills "string.split"-function, beeing called with invalid parameters. I don't think that function is used anywhere by WolfHUD (might be indirect, cannot ssay for sure...) So I doubt I can do much about that, as the callstack isn't really helpful here  :(

**Comment by Tatsugi** [comment]
Hm, after "official" update (from ingame updater) all works fine, but I always checking this site for updates and downloading new builds no matter if it's bring useful fixes or not, just in case, but after last (previous) update (that related with something like "AI stop icon") this crash starts. So, I started to play with friend and our first heist was Goat Simulator, so I thought, that it cause only in this DLC mission, but after disable WolfHUD and finishing this heist we start another heist - Bank Heist, and I wanted to test for crashing with WolfHUD on this heist, and it was, so I renamed the title. :)
If second not related with WolfHUD then it can be because of any other mods or just game bug.

**Comment by Kamikaze94** [comment]
Yeah, already tested with a mate.
The Error happens, because the drill screen gets initialized, even if there are only unplaced drills on the map.
The problem is, my code tries to check for the skills, but Overkill seems to have decided to initialize the drill with an empty (=nil) upgrade table.
Their own function for compairing those to the given players skills doesn't check if the skills are set, so that makes that function crashed.
It seems to work, because Overkills code only calls the function at a specific point.

Currently about to test some solutions to that problem, and deciding which way to go.
I'll tell you, once I upload a solution...  :)

**Comment by Tatsugi** [comment]
The strange thing that in official build I don't get crash although you don't re-code it, but began getting crash after fix «Bot "hold position"».

**Comment by Malidictus** [comment]
The official build you get through auto-updates is older than the build on GitHub. The one here had a fix for a crash issue related to bots being ordered to hold position, which is the build that was crashing. And yes, I was coming here to report the same issue.

With the new version I got off of GitHub, I've seen no crashes whatsoever, however. That specific issue seems to have been fixed. I'm just curious what caused it, since it seemed to crop up when you fixed the "hand" icon crash :)

**Comment by Kamikaze94** [comment]
Nah, popped up shortly after the Bot Icon fix, after commit 5ead9be9c153f3ac09b416d6e05ccfec8fdd8b9d, which fixed the blueish color of drill timers you can upgrade.

Problem was, Overkill doesn't initialize the upgarde  data of the drill properly, but their own function to check if its upgradable doesn't check if that table got set up properly.
It's working for them, as that function is only used on the place/fix interaction of Drills.
But since drills (and its display panel) get initialized when the map is loaded (thus probably the always active collision boxes), my code tried to check with the incomplete table and the function that expected a fully setup table.

The result was the mentioned crash log.

Hope that clears thing up, on what was actually happening.
And thanks for confirming, that it works :)

**Comment by Tatsugi** [comment]
So, if it related to drills then in heists without drills in theory should not crashing (ex. Cook Off, Rats D1/D3...)? Though I can't test it because I already downloaded fixed version.)

**Comment by Malidictus** [comment]
Thank you kindly, that explains the problem quite well. And so much for Overkill's "Mod makers can take shortcuts our programmers can't afford" spiel. With every update, it seems like Overkill's own programmers take shortcuts that mod-makers then have to fix :) But yes, the changes do seem to work.
