### ISSUE TITLE
payday 2 wolfhud crash i pas tab on crime spree

### ISSUE THREAD

**Issue by jan96dk** [Kamikaze94/WolfHUD#510]
recreate_right_original() @mods/WolfHUD/lua/TabStats.lua:164
recreate_right() @mods/WolfHUD/lua/EnhancedCrewLoadout.lua:610
init() lib/managers/hud/newhudstatsscreen.lua:82
new() core/lib/utils/coreclass.lua:35
_setup_stats_screen() lib/managers/hudmanagerpd2.lua:1057
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
show_stats_screen() lib/managers/hudmanagerpd2.lua:1067
set_stats_screen_visible() lib/units/beings/player/playerbase.lua:166
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:848
update_original() lib/units/beings/player/states/playerstandard.lua:414
update() @mods/WolfHUD/lua/BurstFire.lua:212
lib/units/beings/player/playermovement.lua:275

**Comment by Vlad-00003** [comment]
Tubs up. I've lost crime spree due to this(

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:606: attempt to index a nil value

SCRIPT STACK

recreate_right_original() @mods/WolfHUD/lua/TabStats.lua:164
recreate_right() @mods/WolfHUD/lua/EnhancedCrewLoadout.lua:610
init() lib/managers/hud/newhudstatsscreen.lua:82
new() core/lib/utils/coreclass.lua:35
_setup_stats_screen() lib/managers/hudmanagerpd2.lua:1057
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
show_stats_screen() lib/managers/hudmanagerpd2.lua:1067
set_stats_screen_visible() lib/units/beings/player/playerbase.lua:166
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:848
update_original() lib/units/beings/player/states/playerstandard.lua:414
update() @mods/WolfHUD/lua/BurstFire.lua:212
lib/units/beings/player/playermovement.lua:275

**Comment by VolkJ-VJ** [comment]
During the launch of any robbery, after the boot, crash appears
===
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3676: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3674
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3674
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3547
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3547
@mods/WolfHUD/lua/GameInfoManager.lua:3547
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() @mods/P3DHack Free/Free_P3DHack_New/Hooks/Tools/Util.luac:0
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

**Comment by Vlad-00003** [comment]
@VolkJ-VJ, you are outdated. This is not realted to this specific issue and was already fixed.
