### ISSUE TITLE
WolfHUD Tab Stats is not compatible with Lobby Player Info mod anymore.

### ISSUE THREAD

**Issue by PJzuza** [Kamikaze94/WolfHUD#575]
- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

In the past. WolfHUD has a function to rearrange Lobby Player Info mod like the picture below.
![Imgur](https://i.imgur.com/hWkYYrg.jpg)

Now the Lobby Player Info has been updated and the WolfHUD tab stats it is not compatible with Lobby Player Info mod anymore. Instead they are overlaping each others.
![Imgur](https://i.imgur.com/9UkY5RX.jpg)

So if possible can you bring back this feature? Thank you.

**Comment by Shad0wlife** [comment]
This seems to be a bug on LPI's side. LPI seems to still hook into the old "hudstatsscreen.lua" file, not in the new "newhudstatsscreen.lua". That way it fetches the wrong height to show at. So: not WolfHUD's fault imo.

**Comment by PJzuza** [comment]
@Shad0wlife I see. That's true I suppose. I guess either Kamikaze94 or TdlQ fixes it then...

**Comment by HueboWasTaken** [comment]
just asked tdlq, he has no plans on fixing this. Anyone got a workaround apart from just disabling one or the other?

**Comment by HueboWasTaken** [comment]
![image](https://user-images.githubusercontent.com/28763674/33188402-b51b0672-d0ed-11e7-8f38-9cdd1ad97951.png)
fixed by changing the font size in the wolfhud tabstats settings screen to 10, then replacing all counts of "h = font_size or 18" with "h = font_size or 12" in TabStats.lua. This made everything stack nicely but the mask was slightly overlapping, to fix this I changed line 643 to this:

		local padding = -17

and added an extra line under that with:

		local padding2 = 2

then replaced lines 683 and 684 with

				x = paygrade_text:right() + padding2,
				y = paygrade_text:bottom() + padding,

screenshot uploaded is the result.

If you can't be bothered editing that stuff I've uploaded my version here: https://mega.nz/#!vZE2RLzK!f1GRkuTOcaDsqDpP9-fQTYCqY3QuLshngEsenO6C0iA

**Comment by iigravityyy** [comment]
I mean, Wolfhud already includes LPI now. Just uninstall lobby player info. It won't show you the crew skill abilities in planning phase, but it will still show you in the tabscreen and crew information scroll.

**Comment by PJzuza** [comment]
Thank you for every replies here. @iigravityyy Right I forgot that it has been included for a long time... and no we don't have to delete Lobby Player info but only disable the option Show tab stats will do the trick so I'll close this thread as it doesn't an issue in the first place now. Sorry everyone and again thank you very much :)
![Imgur](https://i.imgur.com/dVyPwFG.jpg) 
WofHud Tab Stat Info about skill points and perk decks
