### ISSUE TITLE
Suggestion: Include a .pdmod for Linux Users so that they can use Driving HUD & Fed Inv too

### ISSUE THREAD

**Issue by dribbleondo** [Kamikaze94/WolfHUD#58]
My idea is to include .pdmod for the single texture related to the Driving HUD, and another .pdmod for the Federal Inventory textures. I have the Linux Version of Payday 2, so it'd be easy for to test if this works.

**Comment by Kamikaze94** [comment]
Hmmm, sound like a good idea :)
Got the WolfHUD Textures done.

For the Federal Inventory one, Bundle Modder alwys gives me some weird warnings, finalized by a crash of the Ionic.Zip because it detects some empty replacement strings.
The file format should be okay, so no clue currently, what the problem there is....
I added the lines manually, because damn, I don't wanna add more than 500 entries through that messy "one at a time" UI.

_EDIT:_
Found the problem. It was about the textures of newer DLCs, the ones that we don't have an updated hashlist for.
You can overwrite them via mod_overrides just fine, but BundleModder just throws some "null reference" errors....
Got a version together with the working textures included.
<Add link here, after upload finishes>  ;)

**Comment by dribbleondo** [comment]
I've already tested a version of DrivingHUD I made myself (It's literally one file in the .pdmod), and I'll test Fed Inv later today. 

If you want to release these with the main download, you may want to make it clear in the readme and the .pdmod descriptions that they are for Linux users as there is no Mod_override support, so patching them in is the only option.

**Comment by Kamikaze94** [comment]
Quick update:
Added manual download links for the mod_override and PDMod variant to mod descriptions on Paydaymods and LastBullet.

**Comment by Demiu** [comment]
I know this is closes but could the .pdmod files for Federal Inventory and WolfHUD Textures be updated to lastest version?
