### ISSUE TITLE
End of heist crash 

### ISSUE THREAD

**Issue by MrTactigles** [Kamikaze94/WolfHUD#64]
got this right when the money screen came up, it is not a consistent crash only happens once in a while. 

Current thread: Main
Script stack:
           _update_waypoints()  lib/managers/hudmanager.lua:1383  
                                lib/managers/hudmanager.lua:586  
                            ()  =(tail  
                      call):-1  ()  
                        =(tail  
                      call):-1  ()  
                        =(tail  call):-1  
                      update()  @mods/WolfHUD/lua/TabStats.lua:769  
                                lib/setups/gamesetup.lua:526  
                            ()  =(tail  
                      call):-1  update()  
lib/setups/networkgamesetup.lua:21  
core/lib/setups/coresetup.lua:529  ()  
                        =(tail  call):-1                                            

---

System information:
    Application version : 1.54.12
    CPU : Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 12.0 
    GPU : NVIDIA GeForce GTX 680M / nvd3dum.dll[10.18.13.6881]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     412184    0MB
    OS : 6.2.9200 () 0x100-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Logitech (Speakers (Logitech G35 Gaming Headset))

**Comment by Malidictus** [comment]
I was just coming to report the same crash. I have what I think is the latest build, but I'll reupdate just in case.

**Comment by Kamikaze94** [comment]
Uhm, whats the actual error message?
You only copied the Call stack, which is better than "Access violation", but the actual error might be more helpful. :)
Thanks in advance!

**Comment by MrTactigles** [comment]
The callstack section is pure ?????

Fri Sep 09 10:15:32 2016


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by Malidictus** [comment]
Might as well post mine in its entirety. However, the error message IS Access Violation :)

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
           _update_waypoints()  lib/managers/hudmanager.lua:1383                    
                                lib/managers/hudmanager.lua:586                     
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  ()                                                  
                        =(tail  call):-1                                            
                      update()  @mods/WolfHUD/lua/TabStats.lua:769                  
                                lib/setups/gamesetup.lua:526                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:529  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by Malidictus** [comment]
I got another one of these crashes, with slightly different line numbers. I'd accidentally posted in the wrong bug report. This time, the crash happened right at the end of the Biker Heist Day 1, just before the results screen. Crash log as follows:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
           _update_waypoints()  lib/managers/hudmanager.lua:1383                    
                                lib/managers/hudmanager.lua:586                     
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  ()                                                  
                        =(tail  call):-1                                            
                      update()  @mods/WolfHUD/lua/TabStats.lua:784                  
                                lib/setups/gamesetup.lua:526                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:529  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by Kamikaze94** [comment]
Alright, took a look at the script stack.
The mention of WolfHUD points to the call of the basegames HUDManager's update function.
WolfHUD hooks in there to update the Statsscreen clock, nothing more.

The crash is actually happening when the game tries to update the waypoints.
So from my perspective, if you remove the hook in TabStats, you'll get the same crash report, without any trace of WolfHUD (and a not working clock, obviously, ^^).

That function is hughe monolitic (read "not moddingfriendly") function, that changes and modifies a lot of panels and fields, without any checks for their existence. setting a single field to an unexpected value or nil would cause that function to crash.
This is probably fine, as long as you can guarantee all those values exist and are valid. But when modders come in, changing certain functionalities, or the game gets supported for an extended period of time, QA has a lot to do with testing all certain waypoint-szenarios, let alone all szenarios for all of the other functions working in a similar way. One guy forgetting to set one of those values, because it isn't needed or unnecessary for what he wants to do, can cause problems.
I'm not even sure, it's not a (probably rare) base game bug.

All in all, there isn't much I can do for you.
Unless we would know exactily whats happening (or at least how to trigger that bug reliably), it's really impossible to fix.
(If there is a known way to trigger it, one could hard-overwrite the function with its original decompiled version and add some log commands every few lines, to at least narrow down which part of the function (170 lines) is causing the problem.)

**Comment by Malidictus** [comment]
Question: What do you mean when you say "update waypoints?" It's possible that this is a conflict between WolfHud and something else I'm running, as happened with Full-Speed Swarm last time. Can you explain what you believe the issue is, so I know what to look for in my installed mods?

Other than that, I understand - probably not a WolfHud bug. Would it do to keep logging what I was doing if I run into that crash again?

**Comment by Kamikaze94** [comment]
The HUDManager is actually responible for adding, maintaining (updating) and removing all waypoints. It ahs a function for all these steps. Yhat's crashing you is the HUDManager:update_waypoints(...) function causing an access violation. Waypoints themselfes are actually not a seperate class (like anyone who heard at least a single lecture about object oriented programming would handle it), but a simple table within HUDManager.
I'd suspect it beeing a basegame crash, because it seems to be always happening at the end game, when waypoints get probably removed. So there might be a problem with removing waypoints, probably only appearing if they get removed while the update function is beeing called...?
If thats the case, a simple solution would be, the HUDManager:remove_waypoint(...) function would only flag that waypoint, that it can be removed, and the update_wypoints function will remove it on its next call. barely work, and as update functiuons are called around every 0.1 seconds, (probably framerate dependant :), the waypoint will not be there noticeably longer.
Alternative, more workaround solution would be, the update_waypoints-function setting a flag at start, resetting at its end, to block waypoints_removals. But that would require more work, in order to remove them after reset.
Solution, I would use at most, would probably be, migration Overkills messy waypoints code, to actually create and remove those waypoints from the WaypointsManager (Custom class by Seven, modified it a little, currently used for those damage popups).

 If the issue is related to other mods, it would be one, either modifying HUDManager:add_waypoint or HUDManager:remove_waypoint (if it would change the update_waypoints function, it would be in that Script stack...)
or anywhere modifying the "waypoints"-table of manager.hud ('self' within that class).
That would be the szenarios, where you could modify (and break) those waypoints externally.

Hmm, until now, the most information I got was: "Happend at the end of the mission."
If you get it too appear somewhere during the mission, I guess that would be interesting news to think about....  :)

**Comment by Malidictus** [comment]
I ran a "find in folders" text check via Notepad++. The only thing which do anything with HUDManager functions that isn't WolfHUD is TdlQ's Enhanced Hitmarkers, and even then those just modify HUDManager:on_damage_confirmed(kill_confirmed, headshot). That sounds like a base-game crash, but I'll keep an ear to the ground for reproduction steps. However, it really does seem like that specific crash only happens at the end of heists before we get to the results screen.

If I crash with it again, I'll let you know how and when.
