### ISSUE TITLE
Some questions and suggestion for Unseen Strike countdown.

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#66]
I noticed that some files was deleted in latest builds: **SentryTweaks.lua**, **WeaponLasers.lua** and **hud_info_adv.json**. Are they doesn't need anymore and why?
Also I noticed in last build that you added a skill names in Skill Trees, maybe you add an option to (don't) show skill names (like _Inventory box names_ and _Real weapon names_)?
Can you add an option to disable entire character/mask icon in TabStats?
What exactly do "Loot screen delay"?

Suggestion: Can you add a countdown for Unseen Strike's crit time in Buffs? Maybe I don't understand something but after taking damage it must starts a countdown for crit in 6/18 sec (Basic/Aced); or it starts after waiting 4 sec without taking any damage? Maybe this skill is bugged, don't know, Basic or Aced seems the same for me, same icons.

(Hope some of my sentences don't seems so impudent.)

**Comment by Kamikaze94** [comment]
_SentryTweaks.lua_ was renamed to _EquipmentTweaks.lua_, when ECM and TripMine changes were added.
_WeaponLasers.lua_ was renamed to _WeaponGadgets.lua_, because it also changes flashlight range/angle and turns your viewmodel for angeled sights.
_hud_info_adv.json_ got removed due to the restructure and addition of the Buff menus, that allow you to enable/disable every buff on its own.

For the skill tree names, I tried to make them not too intrusive, by setting the oney not selected a lower alpha. Actually, I updated the weapon names with some similar code, for a similar reason.
But yeah, probably gonna add an option for that...  :)

For TabStats, not sure, as there will be just a gap of unused space, or I stretch the money stats across the whole panel, but that could make it harder to stay in one line..... What's the problem with the icon? 
Is it not pretty enough? :P

Loot screen delay skips the loot screen X seconds after everyone has gotten his card. (setting it to 0 disabled this.)

The Unseen strike buff is showing up different than the skill description tells you it works.
Back when updating with one of Seven's new versions of HUDList, I thought, that it cannot be correct.
So I fixed the function, and it looked like the skill description says.
But from reading the code, I think the current implementation is correct.
Even Enhanced Hitmarkers shows me for example crit hits, even if you stand a minute in a corner, and then shoot someone....
As long as you don't take damage in the last 4 seconds, it increases the duration of the effect. endlessly. 
If you take damage it instantly takes the effect away. And yes, this basically renders the Ace useless.
Check out the code youself, if you want:
https://bitbucket.org/YaPh1l/payday-2-lua/src/a65a4a353a77ab683f062d287217730718d1bc9e/lib/player_actions/skills/playeractionunseenstrike.lua?fileviewer=file-view-default

**Comment by Tatsugi** [comment]
Then maybe you rename "Loot..." to "Card screen delay"?)

Char/Mask icon... maybe I'll accept it (that huge), but all Char/Mask icons have different colors, I prefer it in one color - always white or grey so it will be not so motley.

You said to look at the code myself, but I don't understand this "language", I'm not programmer/coder.)
If I get you right, this skill in Basic and Aced works the same now - endlessly until I take a damage, that's right?

About Advanced Assault Banner, can you do so that assault wave progress will synced atleast between WolfHUD users (how it realised in Carry Stacker Reloaded)?

And in latest build I found typo in < General HUD Panel -> Killcounter Options >, and you can see how this menu looks:
Player killcounter color - Select the color **_yor_** your killcounter.
Show player accuracy - Display your current accuracy **_or_** your HUD.
Teammate killcounter color - Select the color of the killcounters **_or_** your teammates.
![20160915143006_1](https://cloud.githubusercontent.com/assets/19766576/18548507/b70dbd96-7b51-11e6-9997-ce645ae871be.jpg)

**Comment by Kamikaze94** [comment]
1.) renamed.
2.) Hmm, maybe I can bind that to the TabStats color option...
3.) Yep, looks like the Ace version of that skill does nothing at the moment. Just a waste of skill points
4.) I looked a little into the network handling and created a small sample to sync usage of WolfHUD + ECM Feedback times and wether the assault is locked or not. Disabled in the lua by default, as it's completely untested currently. Might add other Host Only Information, if it turns out working...  ^^
5.) Thanks, updated :)

**Comment by Tatsugi** [comment]
Okay, thanks for your hard work.)

**Comment by Tatsugi** [comment]
So sad they are fixed that and now starts countdown. First nerfed Frenzy, now that. :(

**Comment by Kamikaze94** [comment]
How dare they,  fixing the bugs!!! xD
Speed Racer Minigun, never forget <3
