### ISSUE TITLE
Crash when ECM is placed and you're not the host.

### ISSUE THREAD

**Issue by flxlib** [Kamikaze94/WolfHUD#694]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

When a ECM is placed, the game should resume normally.

# Current Behavior

Crashes if an ECM is placed and you're not the host

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Join someone's else stealth
2. Ask someone else to place ECM
3. Crash.

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

```
Application has crashed: C++ exception
[string "lib/units/beings/player/playerinventory.lua"]:973: attempt to index a nil value



SCRIPT STACK

_start_jammer_effect() @mods/WolfHUD/lua/GameInfoManager.lua:3332
sync_net_event() lib/units/beings/player/playerinventory.lua:958
lib/network/handlers/unitnetworkhandler.lua:1576
```

</details>

**Comment by eXCoreX** [comment]
Yeap, encountered the same crash, exception and script stack are the same.

**Comment by Kamikaze94** [comment]
So, from the looks of it, this crash is caused by missing upgrade values in PlayerInventory:get_jammer_time() function (If you are not running the hacker perk deck). 
I don't see how WolfHUD would cause this however, so I think it might be a basegame problem, that will get fixed at some point.
I just pushed a small update that should take care of the problem until that happens...
