### ISSUE TITLE
COUNTER FEIT money....fix.....

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#70]
![20160919023602_1](https://cloud.githubusercontent.com/assets/21234977/18617777/017994cc-7e13-11e6-9940-30b9322005cf.jpg)

fix please... money....

**Comment by Kamikaze94** [comment]
Yep, because the bag name is too long. Recently added the ability to move the HUD panels on the x-axis.
To prevent the overlapping of the bag name with the Player HUD, it gets moved up.

Turned out to be a pain in the **** to keep track and check for all overlapping and resolving it, without making it look worse than before.... decided to go with more simplistic options. The current version now allows to set the panels to the left, wight or center, which should be the most comman and practicable settings here.
