### ISSUE TITLE
Is that a problem?

### ISSUE THREAD

**Issue by Vynnye1337** [Kamikaze94/WolfHUD#710]
Hi! I launched PAYDAY 2 after a few weeks without playing and got this message (printscreen bellow) from WolfHUD. I updated WolfHUD manually already, it's not crashing anymore, but the message still there. A couple mods have a similar message too and cannot self-update.

![image](https://user-images.githubusercontent.com/37525336/44932927-9a694280-ad3d-11e8-9eb2-db54c6668662.png)

Sorry for my bad english, I hope someone can clarify my doubt.

Thanks in advance!! :3

**Comment by MEXAHOTABOP** [comment]
version on paydaymods from far 2016 and since this moment they changed checking by version in file to hash of mod compare
but in far 2016 no one think about this and they not made hash for wolfhud and so just cannot compare with existen install 

but you not must be sad about this since version from paydaymods will not work anyway because too outdated

**Comment by Vynnye1337** [comment]
It's the latest version from GitHub. As I said before, I manually updated my WolfHUD with the latest version, since the older one was crashing my game. What I'm trying to say is, why this message still shows up since I've updated my WolfHUD and BLT? It's not fu***** up with my missions or anything else, I'm just curious cause I got another mod with a similar message too, and I had to manually update this mod too, cause the auto-update was not working, neither on older version of WolfHUD.

Thanks for you comment @MEXAHOTABOP.

Again, I'm so sorry for my bad english. :3
