### ISSUE TITLE
Crash when starting a heist

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#74]
As I said in the MIC thread, I downloaded the latest version of WolfHud from GitHub, and it's crashing on startup for every heist. Crash log as follows:

Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:3775: attempt to perform arithmetic on field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

**Comment by Kamikaze94** [comment]
Happens because of the change in the CustomHUD Panel positioning. 
(WolfHUD Options > General HUD Options > Player Panel/Teammate Panel)
Restet you settings, change those settings ingame once, or look for "PLAYER_POSITION" and "TEAM_POSITION" in your Payday 2/mods/savesWolfHUD.txt file and make sure those are set to a (integer) number from 1-3 (left, center or right).

**Comment by Malidictus** [comment]
Thank you! I changed those settings back-and-forth and am now able to play the game just fine.
