### ISSUE TITLE
[Suggestion] Icons near player's panel to indicate important skills. 

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#75]
Would it be possible to have icons near a player's panel to show that they have team skills like Inspire (Basic/Aced), Drill Upgrades (Auto restart or time decrease), Faster Locking, Gambler Health/Ammo Regen, etc. 

Just any skills that help the team if they were to do them instead. For example,  I can then know that player X has drill skills and can call on them to drill rather than asking everyone and hoping they respond.

Perhaps these icons could also or instead be above players heads, right where their names and Infamy are displayed.

**Comment by Kamikaze94** [comment]
The problem here, is, how to know which skills a player has?
The amount of skills that get synced at the game start is pretty low.
As far as I know, drill skills, ECM skills, etc get only synced to the host and only if your client requests a placement od that gadget.
At the start, evreyone only knows the absolute mandatory skills from other players, like the green teambuffs in HUDList Buffs.

So I could display other palyers drill skills for example, but only if you are host and the client has placed at least one drill already. I don't think that would be of much use tho.

Alternative I could fetch a players skills form pdstats or FBI Files, but then we havethe problem, of how fast they get synced on a profile change. From my experience, that will take far too long to be useable in that case.

Last resort would be syncing them manually within WolfHUD, but that would obviously only work with players that are using WolfHUD as well.

All in all, it's not really easily doable, and probably not woth the hassle.
Thanks for the post, but I guess, I'll pass on this one.... 
(Unless there are some serious changes, on whats synced and when. Unlikely, but not impossible :)
