### ISSUE TITLE
bug? Driving...?

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#78]
![20160925030819_1](https://cloud.githubusercontent.com/assets/21234977/18810295/a3ceb86a-82cd-11e6-8f8f-4a2fd8322dbc.jpg)
![20160925012222_1](https://cloud.githubusercontent.com/assets/21234977/18810296/a44e4ed6-82cd-11e6-9b8f-2f7cae5b1aa1.jpg)

Driving....mod bug?

**Comment by Kamikaze94** [comment]
Hmm, possible, as you might have seen, I completely rewrote the DrivingHUD mod, to make repositioning possible (maybe add rescaling in the future, not sure....)
Anyways, only tested with Bots, so I couldn't test all scenarios, as bots never get out of the vehicle if you are inside + only wear their defaul mask....
What you see there is the "Missing texture texture", so maybe getting the mask texture fails for some masks, of it has to do with the conditions of showing/hiding the icon.

I'd guess for the first one, as it appeared 2 times on the same person (probably wearing the same mask...)
Do you know which mask that was?
Thanks in advance :)

**Comment by Tatsugi** [comment]
If it was after latest patch, can this mask be a Housewarming Party Hat?

**Comment by Kamikaze94** [comment]
Nah, Party hat was working fine for me....
My best guess would be the mask_id in that players char_data wasn't set for some reason, or there are actually masks, that use some custom texture path instead of the normal one.
Actually gave it a fix, by checking for the "custom_texture" field of the tweak_data (looks like no mask has that one set, but it gets checked by other functions to get mask textures, so probably not too bad to actually check for), and use default char mask as fallback, and alienware mask, as fallback, if the character isn't set too....^^
So, missing textures shouldn't happen anymore, I hope :)

**Comment by hud8614** [comment]
humble bundle #1 mask......
http://kirakblade.deviantart.com/art/PAYDAY-2-the-Crossbreed-460594536
