### ISSUE TITLE
Advanced Assault displays no Text

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#82]
![20161006042254_1](https://cloud.githubusercontent.com/assets/21234977/19128594/008fd138-8b7f-11e6-9599-acd1982601a6.jpg)

ASSAULT MARK.....BUG?

**Comment by Kamikaze94** [comment]
Happened through the whole assault or just at the beginning?
Does this occur every time or just sometimes? (Just checked, and in Offline and Online solo the assault data appears for me....)
And do you have enabled NetwokHandler.lua, by removing the first line? 
(Because thats one of the bugs it causes currently, and one of the reasons it is disabled by default....)
