### ISSUE TITLE
Bug in preplanning map.

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#89]
There is nothing on the map, even selected assets. Bug causing when I, as Client, enter preplanning map before loading a Host.
I've already reported it at PD2 forum, but they're can't reproduce this bug, so I thought that it can be causing by any mods, WolfHUD for ex., as usual (sorry :D).
This is my thread: http://steamcommunity.com/app/218620/discussions/14/350544272211165405/
http://images.akamai.steamusercontent.com/ugc/438364144690532947/5DB62F60FD45F7962BAB62267C2E6AC2CD972369/

**Comment by Kamikaze94** [comment]
Hmmm, strange....
On your screenshot, the Host unlocked the Bodybags. Did he buy that after or before you had loaded for him? And is that happening if you unlock assets after loading too?
The rare times I manage to open the Preplanning before I'm done loading, are the times I cannot even purchease anything there. Going out and back in after loading normally fixes that. Never really payed much attention to the icons on the map in those cases though.
I don't think WolfHUD is the cause here, but I'll keep my eyes open the next times I'm playing I guess :)

**Comment by Tatsugi** [comment]
He bought it while I'm been in preplanning map, but even after reopen map I can't see any icons on that, but I forgot to mention - anyway I can buy assets, just can't see where it will be deployed.
A short time ago (after Day 2 update) I don't seen this bug. Maybe that was just an "accidental" bug.)
