### ISSUE TITLE
TabStats: LPI overlapping with Extended Inventory

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#90]
![20161009055048_1](https://cloud.githubusercontent.com/assets/21234977/19215923/7ee9f34c-8de6-11e6-9918-be4ace859857.jpg)
Extended Inventory 
big;;;;;;;;;;fix please....

Tab "Extended Inventory" Right -> Tab "Extended Inventory" Left please.....

**Comment by Kamikaze94** [comment]
Ah, thats because I already added the entry for the new medic enemy...^^
Havn't thought about LPI yet though.
Hmm, moving Extended Inventory to the left shouldn't be too easy, by how those panels get created, :(
I'd like to remove extended Inventory for some time now, but it would require to have HUDlist Show BodyBags enabled...or I'd need to add the bodybags amount to CustomHUD equipment.
Any opionins on that?
_(Btw, what the heck are you doing on those titles? lol....)_

**Comment by Kamikaze94** [comment]
Disabled the "Extended Inventory" Text for now, so the LPI Infos stay visible, :)
Might change that in future once I find a better solution.
