### ISSUE TITLE
Minimizing the game

### ISSUE THREAD

**Issue by Bluetexon** [Kamikaze94/WolfHUD#92]
Hi,
I have installed WolfHUD and I love it.
But I have discovered a bug, which causes the following:
After I leave a lobby or after I'm finishing a heist, my game minimizes.
Is there a option, which I have to turn off?

Thanks and with best regards,
Bluetexon

**Comment by Kamikaze94** [comment]
Did it successfully install/update a mod_override named "WolfHUD_Textures"?
This contains some textures for DrivingHUD & HUDList. Since BLT doesn't allow me to add mandatory mod_overrides, WolfHUD tries to create a folder for it, with revision 0, so BLT will detect a new update and ask to install it.
Sadly I cannot create a folder in another way than by executing a CMD command, which causes the game to minimize.
So if it fails to create said folders for whatever reason, it will try again and again.
Fix is simple:
1. create a folder named "WolfHUD_Textures" withing your "mod_overrides"-folder.
2. create a textfile named "revision.txt" in that folder.
3. open the textfile and write "0" (without quotations) in it.

**Comment by Bluetexon** [comment]
Cool, I've done that and now it's working.
Thank you for your help and keep up the good work!

Greetings,
Bluetexon
