### ISSUE TITLE
Crashes Game

### ISSUE THREAD

**Issue by Paramyxovirus** [Kamikaze94/WolfHUD#97]
Just got an update for the John Wick Weapon Pack, and my game crashed as soon as I started it again.
Dunno what happened, but when I removed WolfHUD it worked just fine. In the meantime, I don't really want to use some other HUD because it would be too cluttered like in PocoHUD or not enough info like in most HUDs. Is there any other hud that you would recommend in the meantime?

**Comment by Didjahtul** [comment]
Goto your payday mod folder. Delete Wolfhud. Then download the current build and extract again.

**Comment by Kamikaze94** [comment]
Yep, the update archive was missing the "WolfHUD" root folder, and came with the components inside directly. BLT Updater did extract it and deleted WolfHUD's "loc" folder.The first causes all files beeing directly inside the mods folder. The second beeing resposible for the crashing.

Already posted about this issue on paydaymods and lastbullet (didn't came into my mind, people on official build would ask here for help...) and 2x on Steam.

The fix for this is basically what @Didjahtul already said.
Remove the cluttered around files and manually install the current version of WolfHUD.

Sorry for the inconvenience, :(

**Comment by Paramyxovirus** [comment]
Alright, thanks for that :D I was super worried that I did something to my game.
