### ISSUE TITLE
TabInfo text glitch - blurred for an unknown reason.

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#98]
![20161021152956_1](https://cloud.githubusercontent.com/assets/19766576/19600498/f575b7be-97ad-11e6-97b0-df61ef114174.jpg)

**Comment by Kamikaze94** [comment]
Can confirm, only happens with active mutators.
Mutators and Tabstats both resize the panel. The horizontal bar that gets placed at the bottom, if texts are longer than the panel here, bugs out and creates that "blurred" style....

**Comment by Tatsugi** [comment]
Is it a normal or "disease"? xD

**Comment by Kamikaze94** [comment]
Uhm, was either rearranges constantly moving that bar up and down causing those trails, 
or it doing those moving once, and the engine failing to properly update the panel? 
Since I never had the second issue, I'd say probably the first one.

Fixed that by making the day_description big enough, so the Vanilla code should keep enough space for TabStats.

Why Change a file, that doesn't need to be changed? ^^
